### ISSUE TITLE
v0.6.6 will freeze sometimes.

### ISSUE THREAD

**Issue by JackWang47** [maruos/maruos#106]
Hi!
Happy to see maruOS for nexus5 update at this time.
I just update my nexus5 from v0.4.1 to v0.6.6.
And I am happy to see android 8.1 with so many new function on nexus5 at first.

But after all I decided to restore the v0.4.1 backup.

For one reason,it took me some time to make the debian support display Chinese.
It's ok,I just don't want to do it again.

For another,android8.1 can't work smoothly on nexus5.

**Comment by pdsouza** [comment]
Hi Jack, did you install Google Apps after installing 0.6.6? I noticed that the Nexus 5 is very slow on the first boot after installing Google Apps since Android will optimize all the Google apps in the background, which can take an hour or sometimes more. Usually the N5 will become much more responsive after that initial optimization time. 

But yes, I do agree that 8.1 is slower on the N5. Maybe we should look at supporting N5 on Android 7.1 / Lineage 14.1 if that's still smooth? It would also fix #104.

**Comment by JackWang47** [comment]
Thanks for the reply.
No,I didn't install any apps,
I try v0.6.6 again today. And yes I do feel better after a while.

But still v0.4.x was better. I think support N5 on Android 7.1/Lineage 14.1 may be a good idea.
