### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ghost** [maruos/maruos#34]
Plz can u port this to the samsung galaxy tab 4,I wana try it out.
can u also make the os avalabale as a dual boot for peopel like me who don't have a port for microhdmi plz.
I want this to be a feature when the project is open source

**Comment by ahstro** [comment]
Re. dual boot: MaruOS can be run with MultiROM, here's [a forum post](https://groups.google.com/forum/#!msg/maru-os/TGCHBXxW45c/RdpU3a3CCQAJ) explaining how that works. I'm not sure how that will help you if you've not got the necessary hardware though.
The ROM is sure to be ported to more devices as it matures and is more and more open sourced, but I can't say anything more about that since I'm not that invested in the project.

**Comment by chevdroid** [comment]
For Device Ports you can look here : https://groups.google.com/forum/#!topic/maru-os-dev/YufKu3w2xkQ

And with a bit luck, a dev will do a port :)

**Comment by wjrivera** [comment]
Can you make phone calls after installing Maru OS on the Nexus 5?

**Comment by chevdroid** [comment]
Hi wjrivera

All hardware on the Nexus 5 (Wifi,Bluetooth,GSM,GPS) is working with Maru OS, its based on stock AOSP, so yes you can make phone calls!

**Comment by utzcoz** [comment]
If anyone has interesting in porting MaurOS forsamsung galaxy tab 4, you can follow https://maruos.com/docs/developer/#structure for it. If you have question about porting, you can create a new discussion at this repo for it. Feel free to reopen this issue if you have problem.
