### ISSUE TITLE
Wireless Display as an alternative to SlimPort or MHL

### ISSUE THREAD

**Issue by Redsandro** [maruos/maruos#4]
With [Ubuntu OTA 11](https://www.youtube.com/watch?v=NUiEnTLFFdk) comes wireless display capabilities using dongles using I believe MiraCast. It opens up a whole lot of non-MHL devices to be used as desktop computers.

Source: http://insights.ubuntu.com/2016/06/01/over-the-air-11-weve-gone-wireless/

**Comment by pdsouza** [comment]
Thanks for the request! 

Very cool. Latency looks pretty good in that video. This was brought up many times in the private beta program, see the similar Feature Request 13 in the [beta program bug/feature sticky](https://groups.google.com/d/msg/maru-os/_TL63qbNsKs/urgXBMQ4DwAJ).

**Comment by Redsandro** [comment]
Note that MiraCast is a standard, while ChromeCast is a product.
http://www.pocket-lint.com/news/133437-miracast-explained-how-is-it-different-from-chromecast-and-airplay

Not sure if the MiraCast support is in the AOSP version, but there are open source implementations OpenWFD and MiracleCast. 

Not sure how much overhead there is but both the latency and the refreshrate are pretty sweet in the Ubuntu convergence.

**Comment by snacdaws** [comment]
Would love to have this feature so I could use the desktop screen while still using Windows as I only have 1 hdmi monitor

**Comment by EUA** [comment]
Overhead has to be minimal in term of CPU because almost all modern phones has a avc/h264 encoder circuits inside and could encode the stream without using at least much CPU. But this probably harms WiFi/internet connectivity in return. But I see it is only way because many modern devices has no MHL ports in it.

**Comment by Redsandro** [comment]
> this probably harms WiFi/internet connectivity in return.

This is true. But when driving through Norway, you quickly learn that a way is better than no way. :smile: 

Besides, I think the Ubuntu team thought this trough. For working on documents, DTP, Blender etc you don't really need Wifi all that much (or at all). When ones job is 'working on the internet', one could make sure they buy an MHL phone.

**Comment by poVoq** [comment]
Miracast is a bit of a mess under normal Linux (Ubuntu Touch claims to have it working better, but I never got it to work on my UT Nexus4).

Maybe a way would be to channel the Debian desktop back to Android through this app: https://play.google.com/store/apps/details?id=x.org.server&hl=en
and then use the excellent ASOP miracast support? I guess in general it would be interesting to have an option to see the Debian desktop from Android as well.

**Comment by Redsandro** [comment]
@poVoq I think channeling x is something that should be avoided. As I understand it, x - while being awesome for many reasons - is carrying the legacy, latency, and dead weight of ancient times and will slowly be deprecated. The X11 core concepts are 30 years old after all. Using x will make it harder to use this setup with other distro's. Ubuntu and Linux Mint are bound to switch away from x soon. Ubuntu Touch already switched away from x.

It says a lot that Ubuntu has invested 10 years of R&D in _removing_ x from the equation, _specifically_ for the purposes of going mobile. X is, by design, not suitable for casting. The right way would be to benefit from their R&D and figure out how they got it to work.

Ubuntu switched to Mir claiming it surpasses Wayland in speed and efficiency. According to them, if I recall correctly, Wayland might already be a bit outdated, because the project started out as a rewrite of x called X12.

Of course there is a bit of controversy surrounding (the dual licensing of) Mir but that shouldn't prevent it from being fast.

**Comment by poVoq** [comment]
In general I agree, but for the forseeable future X11 will stay part of the picture and it is also what MaruOS is currently using. So with the above tool it might more or less now and just needs a more streamlined setup.

**Comment by Redsandro** [comment]
Agreed. Something that works is always better than something that works better in theory.

**Comment by poVoq** [comment]
That should be the official slogan of MaruOS :) (compared to Ubuntu Touch for example...)

**Comment by poVoq** [comment]
https://github.com/albfan/miraclecast
could also work directly.

**Comment by krazedkrish** [comment]
Eagerly wating for wireless display connection.
😄

**Comment by pdsouza** [comment]
We support wireless in 0.6! It has been tested on DisplayLink and Chromecast so far. You can try out our builds early [here](https://github.com/maruos/builds/releases).

**Comment by poVoq** [comment]
Awesome! Could you shortly elaborate how it was done technically given the above discussion we had? Thanks!

**Comment by Redsandro** [comment]
This is great news!

I would like to take this opportunity to emphasize how annoying it is that the source code is not simply browsable on github. Lot of hoop-jumping necessary.

**Comment by pdsouza** [comment]
@poVoq I decided to entirely dodge the issue of getting wireless to work from within Linux given the messy state of things (as you mentioned). Instead, I add a small patch in Android's display server that will override Android's typical mirroring of the phone built-in screen with Maru's desktop. This modification is at the logical display layer, so it applies to *all* external displays that Android recognizes, regardless of protocol! This lets us piggyback on all of AOSP's external display support, which includes Chromecast. In the end, it was similar to your idea of channeling the desktop back to AOSP and leveraging AOSP's wireless support, although I did it directly within the display server itself, instead of using an app for performance! Hope you get a chance to try this out and give it a test on your wireless hardware!

**Comment by pdsouza** [comment]
@Redsandro Yes, I know. Unfortunately AOSP uses [Repo[(https://source.android.com/setup/build/downloading) to manage the source across hundreds of small git repositories; we split up our code to fit into this AOSP-specific source organization paradigm. I would personally prefer a single monorepo honestly, and I am trying consolidate as much of our code as possible to make it easier to browse. Any ideas to improve this situation is very welcome - please feel free to open an issue for this if you'd like. Anyways, I hope you get a chance to give our wireless support a test run! We should be able to support nearly any device now as long as we have the hardware since we do not require SlimPort / MHL support (although wired is the best experience honestly).
