### ISSUE TITLE
Support for bullhead nexus5

### ISSUE THREAD

**Issue by phlax** [maruos/maruos#42]
I tried using the standard installer from linux, but i get stuck in recovery mode.

Im thinking its because my devices is `bullhead` rather than `hammerhead`. Not sure what the difference is tbh, but wondering if there is a way to use maruos with this device, or plans to support.

**Comment by chevdroid** [comment]
Yes that's why it didn't worked. bullhead is the Nexus 5x from 2015 and the hammerhead is just Nexus 5 from 2013, there is everything from cpu to camera diffrent, so it won't work with this installer.

For more infos for support for other devices please have a look here:
https://groups.google.com/forum/#!topic/maru-os-dev/YufKu3w2xkQ

A Port to the Nexus 5x is planned, sadly the hardware of the N5x does not support MHL or Slimport, so the desktop won't show up on any monitor. There are featureplans for miracast or chrome cast (wireless streaming the desktop to the monitor)
https://github.com/maruos/maruos/issues/4

**Comment by pdsouza** [comment]
@phlax Yep, as Chev pointed out, bullhead and hammerhead are very different hardware. Maru OS will need a build specifically for bullhead for it to work.

Were you able to get your 5X back to your previous setup and working again? You can grab a bullhead factory image from here: https://developers.google.com/android/nexus/images#bullhead. Let me know if you have any issues going back, happy to help.

**Comment by phlax** [comment]
thanks for replies - it shouldnt be difficult to get another image loaded onto the phone - im just disappointed because i purchased it specifically to use with maru.

Feel free to close the ticket

**Comment by pdsouza** [comment]
Apologies that Maru OS does not support bullhead yet! Hope to support it in the future.
