### ISSUE TITLE
Maru Desktop Wouldn't Start

### ISSUE THREAD

**Issue by NigerianExpress** [maruos/maruos#50]
After a clean install with the 0.3 update zip on a Nexus 5 with M4B30X as the factory image, it says "Maru Desktop failed to start" every time I turn it on
My phone is not encrypted, and I'm not using Multirom
ADB logcat:
`01-22 17:00:31.471  2514  2514 D MDesktopSettings: onPerspectiveStateChanged: STARTING
01-22 17:00:31.626   214   235 D perspectived: liblxc returned false for start, possible false positive...
01-22 17:00:31.627   214   235 E perspectived: failed to start desktop
01-22 17:00:31.627   810   840 E PerspectiveService: nativeStart failed
01-22 17:00:31.627   810   840 D PerspectiveService: mDesktopState: STARTING -> STOPPED
01-22 17:00:31.643  2514  2514 D MDesktopSettings: onPerspectiveStateChanged: STOPPED
01-22 17:00:34.703   202   796 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
01-22 17:00:34.703   202   796 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)`

**Comment by pdsouza** [comment]
Thanks for the report.

Can you try rebooting your device? Sometimes there is a race condition after the first boot where the desktop system isn't fully set up. If that doesn't help, please try running a factory reset to force everything to initialize again. If neither of these helps, let me know and I'll walk you through some debugging steps.

**Comment by curiousercreative** [comment]
@pdsouza I've installed a custom kernel (franco) and all is well until I attempt to start Jessie. The toggle is quickly enables and then disables without pause and I receive the same logcat messages as OP (without the audio_hw). Are there further debugging steps to identify the exact cause? I'm fairly confident it's an issue of kernel config, but I'd like to be certain before bothering the kernel developer. Here's the [defconfig](https://github.com/franciscofranco/hammerhead/blob/marshmallow/arch/arm/configs/hammerhead_defconfig) for the kernel I started with, then added the [required kernel config from your wiki](https://github.com/maruos/maruos/wiki/Kernel#define-your-kernel-config). I'm guessing the issue is that my defconfig has the following:
```
# CONFIG_UTS_NS is not set
# CONFIG_PID_NS is not set
```
Problem is, I get build errors when removing them :( So, I'd like to be as confident that this config is the culprit before begging the kernel developer about the build errors with the modified config.

Any help is appreciated, I'm still new to kernel building :)

**Comment by pdsouza** [comment]
@curiousercreative Bingo, Maru OS has a hard dependency on PID namespaces (`CONFIG_PID_NS`) enabled in your kernel config to work. If you have build errors associated with namespaces (common with 3.4 AOSP kernels), I suggest you try cherry-picking this Maru patch: https://github.com/maruos/android_kernel_hammerhead/commit/db861adfcc2f5698b6c0a83c2a963a073cc64598.

**Comment by curiousercreative** [comment]
@pdsouza Thanks very much, that did it! I ended up merging your kernel into Franco's as well: https://github.com/curiousercreative/hammerhead/tree/maru

**Comment by pdsouza** [comment]
@curiousercreative Excellent, glad to hear it worked out!

**Comment by curiousercreative** [comment]
@pdsouza can this issue be closed?

**Comment by pdsouza** [comment]
@curiousercreative Yup, this issue is outdated now, thanks.
