### ISSUE TITLE
iodine: open_tun: /dev/net/tun: No such file or directory: No such file or directory

### ISSUE THREAD

**Issue by Aloento** [maruos/maruos#64]
iodine: open_tun: /dev/net/tun: No such file or directory: No such file or directory

**Comment by dianaxxyyzz** [comment]
Try this : 

mknod /dev/net/tun c 10 200

chmod 0666 /dev/net/tun

**Comment by robgmills** [comment]
I have the same problem (also on Debian Jessie).  The above suggestion did not work because the `tun` device already existed:

```sh
~ $ ls -la /dev/net
total 0
drwxr-xr-x  2 root root      60 Apr 11 21:59 .
drwxr-xr-x 16 root root    3680 Apr 12 20:17 ..
crw-rw-rw-  1 root root 10, 200 May 12 11:00 tun
~ $ mknod /dev/net/tun c 10 200
mknod: ‘/dev/net/tun’: File exists
```
It must have been created by udev.

This problem seems to be common with OpenVPN also.  [One hopeful solution posed on another message board is to simply _reboot_](https://bbs.archlinux.org/viewtopic.php?id=163377).  I had recently run an `apt-get update && apt-get upgrade` and after rebooting, `iodined` started up just fine:

```sh
~ $ systemctl status iodined
● iodined.service - LSB: initscript for iodined
   Loaded: loaded (/etc/init.d/iodined)
   Active: active (running) since Mon 2017-05-15 04:46:19 CDT; 3min 46s ago
   CGroup: /system.slice/iodined.service
           └─811 /usr/sbin/iodined -u iodine -t /var/run/iodine 192.168.99.1...
~ $ ifconfig
dns0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:192.168.99.1  P-t-P:192.168.99.1  Mask:255.255.255.224
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1130  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

<...>
```

**Comment by pdsouza** [comment]
@robgmills Thanks for sharing your solution!

**Comment by utzcoz** [comment]
Thanks @robgmills for sharing solution. If anyone has this problem, you can follow https://github.com/maruos/maruos/issues/64#issuecomment-301429442 to fix it. I will close this issue, and feel free to reopen it if you have any problem.
