### ISSUE TITLE
[Question] Do you plan on supporting intel devices in the future?

### ISSUE THREAD

**Issue by kdog31** [maruos/maruos#68]
a wild thought came to mind last night, if maru could be supported on intel based devices, as a proof of concept would it be possible to use Windows rather than Linux. I say this because even though most people who know how to flash custom ROMs are (i assume) Linux users or are at least familiar with Linux the windows platform is much better in regards to supporting applications. I also say this because I know a number of people whom I have shown this to who own supported devices but as Linux is the other half of maru it breaks the deal for them as they are reliant on applications that rely on the windows platform.

**Comment by dianaxxyyzz** [comment]
Maru os ,can run on x86 but I do not think windows can be run on it unless the cpu supports virtualization .

To run debian ,it does not have to support virtualiation , cause it start debian using same kernel android use .

**Comment by pdsouza** [comment]
Thanks for your question! I definitely agree that being able to run Windows on the desktop side would be great.

However, @dianaxxyyzz is right that although Maru can certainly run on x86 (some work needed for this of course, but certainly possible), this does not mean Windows would be able to run like Linux does right now. The key with Maru is that it uses lightweight virtualization via containers, which is possible only by sharing the same kernel between the host and virtual systems. Android and Linux both share the same Linux kernel underneath, so this works great, which is one reason Maru Desktop is based on Linux. But Windows uses it's own kernel, so Windows would only be able to run in a true virtual machine, and not via a lightweight approach like containers. There are many downsides to using a true virtual machine, in terms of performance as well as ease of bringup due to the need for virtualized drivers.

If you are still curious about using Windows on Maru, you may want to look into running Windows in a true VM on a hypervisor like KVM. This should in principle be possible on Maru by setting up QEMU/KVM-on-ARM on Maru Desktop. A warning that the process is not simple since you will have to build KVM on ARM from source and stuff--I don't think there are any Debian packages for it yet since it is still a WIP. I've wanted to try that for a while now, but I never had the time.

**Comment by utzcoz** [comment]
Porting MaruOS to Android-x86 maybe a choice for intel based devices. There is a more related issue https://github.com/maruos/maruos/issues/40, we will discuss related problems at that issue, and I will close this issue. Feel free to reopen this issue, if you have any problem.
