### ISSUE TITLE
Make the wiki be editable

### ISSUE THREAD

**Issue by ian-kelling** [maruos/maruos#70]
I'm guessing right now, it's set so that only "contributors", people who have had a pull request accepted to this repo can edit the wiki. This makes it harder to contribute to the wiki than the repo itself, which is way too unfriendly to contributors. I see only 2 ways to make it reasonable: 1. change it to be editable by anyone with a github account, like most github wikis. 2. If you want to approve edits, there's no reasonable way to do it for a github wiki, so move the content out of the wiki and into a docs folder with a .md file per wiki page and accept pull requests.

**Comment by pdsouza** [comment]
Thanks for the suggestion--this sounds good to me. I've wanted to open it up before but 1) wasn't sure if anyone was really going to take the time to made edits, and 2) wasn't sure about spam edits. Since you ask though, I assume you would like to contribute to the wiki, which is great! Just marked it as editable for all GitHub users.
