### ISSUE TITLE
HDR+ Camera Support

### ISSUE THREAD

**Issue by forgotpw1** [maruos/maruos#74]
I have been reading a lot about HDR+ lately. I run MaruOS on a nexus 5. Does the MaruOS camera app support this feature? Are there plans to use a version of Google Camera that supports HDR+ in the future?

**Comment by pdsouza** [comment]
Hmm, I don't think the stock AOSP Camera app we ship supports HDR.

Have you tried installing a third-party Camera app that does support HDR? I just tried [Open Camera](https://play.google.com/store/apps/details?id=net.sourceforge.opencamera&hl=en) and HDR works on my Nexus 5 running Maru.

No plans on changing the Camera app at the moment because it should be easy for users to install whichever camera app they like--we just provide the very basic apps to get you started. The Google Camera app with HDR would be great (looks like it was removed from the Play store recently...weird) but that's proprietary and I want the Maru base system to be completely open-source if possible.

**Comment by curiousercreative** [comment]
@forgotpw1 you can also download a build of the stock Google Camera that would have come installed with Marshmallow. This is the version I have installed which still supports Nexus 5 HDR+: http://www.apkmirror.com/apk/google-inc/camera/camera-3-2-045-release/google-camera-3-2-045-2821762-30-android-apk-download/

**Comment by curiousercreative** [comment]
@pdsouza also, can this issue be closed?

**Comment by pdsouza** [comment]
@curiousercreative Thanks for the link to the stock Google Camera app--that's a good option too! Closing this since there's no further action item for Maru.

**Comment by forgotpw1** [comment]
@curiousercreative Thank you for sharing this link. Exactly what I was looking for.
