### ISSUE TITLE
Feature Request: Multiple CPU usage?

### ISSUE THREAD

**Issue by fiveseven808** [maruos/maruos#80]
I don't know if this is a problem of Maru, or a reporting problem, but I noticed when I use a program like top or htop, the system only seems to be using one cpu (out of the quad core nexus 5). 

Is it using all 4 cores currently and it's just a reporting issue? If not, would it be possible to make use of all 4 cores in the future?

Holy crap though, this Maru OS is mind blowing! I'm typing this using midori running on Maru OS right now! 

[Running 0.4]

**Comment by pdsouza** [comment]
Thanks for using Maru and for the kind words!

All cores are enabled for use on Maru Desktop--the issue is that the phone hotplugs cores and I have noticed that it boosts a single core when loads are high. I need to investigate this further, some more detective work by our users here: https://github.com/maruos/maruos/issues/58

**Comment by fiveseven808** [comment]
Hooray! Thank you for discovering the issue and pushing a fix! I can't wait for the next release! I'm super surprised how fast everything seems to run on a single core! Excited to see performance now!
