### ISSUE TITLE
Device goes to sleep when using Maru OS on device

### ISSUE THREAD

**Issue by fiveseven808** [maruos/maruos#81]
So, I know that this is probably a result of the way that MaruOS redirects the bluetooth input, however I noticed that if I use VNC to access maru OS with a bluetooth mouse and keyboard, the screen times out and goes to sleep. 

Would it be possible to fix this? Somehow give MaruOS the ability to send some sort of keep-alive to android so it doesn't shut off the screen? Make it a toggable option since this is probably not desirable for people who leave the phone connected to a screen?

**Comment by pdsouza** [comment]
This should be fixed after user-configurable redirection of input is available in #12. So if you are using VNC on the phone to connect to Maru Desktop, you can choose to use your BT keyboard on the phone/Android, which will keep the screen alive.

**Comment by utzcoz** [comment]
You can enable the device's development mode and make sure the `stay wake` option is open. And then switch the Display's sleep time to the maximum value(`Settings`->`Display`). It works for me without code changes.

**Comment by pdsouza** [comment]
@fiveseven808 This should be now fixed with @utzcoz's patch in https://github.com/maruos/maruos/issues/97. In short, we no longer drop the BT keyboards and mice from Android's input processing layer, so moving the mouse or typing on the keyboard will keep the screen awake. It is available in our [0.6 builds](https://github.com/maruos/builds/releases) already. Note that 0.6 is still technically in testing, but will be released publicly soon if you'd rather wait to get it officially.

**Comment by pdsouza** [comment]
Closing this since 0.6 has been released with this fix. Feel free to re-open if there are further issues.
