### ISSUE TITLE
Device stays in bootloop, recovery not possible

### ISSUE THREAD

**Issue by maartenstolk** [maruos/maruos#85]
Hi,
Thank you for maruos. I really love(d) it.

Phone stays in boot loop since yesterday, not updates or anything could have caused it. Not possible to go back to recovery mode from bootloader (only options are "start", "restart bootloader", "recovery mode" and "Power off", and phone not recognized on PC using Android ADB tool. 

Is there another way to completely swipe memory and reinstall Maru OS? Would love to use my Nexus again, either with or without Maru OS but can't find a way to go back to factory settings given above restrictions.

Thanks

**Comment by TMartinPPC** [comment]
When you device is on the bootloader you'd use fastboot instead of adb. I would suggest downloading the appropriate TWRP img file for your device and fastboot flashing that while in bootloader. After that, you should be able to access recovery. While in recovery you can connect your device to your computer and push whatever ROM you want to flash, whether that be Maru or another custom ROM. When flashing Maru from TWRP, I'd recommend only doing a factory reset (ie after hitting wipe from the main screen, just swipe right). If you do an advanced wipe then flash Maru, it typically reverts back to a stock recovery.

**Comment by montvid** [comment]
See here for the files and instructions.
https://twrp.me/lg/lgnexus5.html
https://twrp.me/asus/asusnexus72013wifi.html

**Comment by pdsouza** [comment]
Closing this as stale. Please feel free to re-open if you have further issues.
