### ISSUE TITLE
Feature Request: update kernel to 3.4.113 2016-10-26

### ISSUE THREAD

**Issue by montvid** [maruos/maruos#87]
Hi It would be nice to update the kernel of maruos to the latest 3.4.113 made in 2016-10-26 as it is not changing anymore. Some custom roms have this implemented like DirtyUnicorns. Would it not be easy to fork their kernel or the one from kernel.org and add maruos bits on top?

**Comment by montvid** [comment]
Maybe a good Idea is to use The Unlegacy Android Project for up to date security and pure AOSP because nexus 5 & 7 don't get love from google anymore? [https://forum.xda-developers.com/nexus-7-2013/orig-development/rom-unlegacy-android-project-t3578301](https://forum.xda-developers.com/nexus-7-2013/orig-development/rom-unlegacy-android-project-t3578301)
Just an idea.

**Comment by pdsouza** [comment]
Thanks for the request!

If it's a clean merge of the AOSP/maruos bits on top of 3.4.113 then I am very happy to upgrade. I suspect it likely should be since there should only be smaller upstream patches on top of the current 3.4.0 kernel we use. Let's definitely keep this open.

Regarding security--Maru already merges in the latest device-independent security patches from AOSP as they come out as detailed on our wiki: https://github.com/maruos/maruos/wiki/Security. I just recently merged in the latest available patches for M and will continue to do so as they come out.

**Comment by montvid** [comment]
Thanks for the reply. The kernel patch is a more or less one time patch because it's an old kernel but the AOSP security patches are monthly so that's a bit annoying. Maru os Nexus 7 2013 is on the February 2017 patch only.
Thanks for the great rom, it seems it is the more or less the only rom running a linux lxc container over android. The oher one being KDE Plasma mobile [http://blog.bshah.in/2016/05/02/plasma-mobile-new-base-system/](http://blog.bshah.in/2016/05/02/plasma-mobile-new-base-system/)

**Comment by pdsouza** [comment]
I believe we are running the latest kernel available for hammerhead now after switching over to using LineageOS as our base. Please let me know if there are newer kernel versions available, as I would like to use the latest I can get my hands on.

Closing, but feel free to re-open if you have further issues.
